/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32l4xx.h"
#include "usart.h"
//#include "stdio.h"

void Debug_Toggle(uint32_t cycles){
    for(uint32_t i = 0; i < cycles; i++)
        __NOP(); // no operations
}

int main(void){
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN; //enable clock for port A
	GPIOA->MODER &= ~(0b01 << 11);
	GPIOA->MODER |= (0b01 << 10);
	GPIOA->ODR = 0b00000000;

	usart_init(115200);
//	printf("Hello World\r\n");
	while(1){
		GPIOA->ODR |= (0b01 << 5);
		Debug_Toggle(1000000);
		GPIOA->ODR = 0b00000000;
		Debug_Toggle(1000000);
	}
}
